CELL_RADIUS = 40
BORDER_WIDTH = 10

WINDOW_WIDTH = 1300
WINDOW_HIGHT = 900

PLAYER_WIDTH = 200 - 2*BORDER_WIDTH
PLAYER_HIGHT = WINDOW_HIGHT - 2*BORDER_WIDTH

BOARD_WIDTH = WINDOW_WIDTH - 2*PLAYER_WIDTH - 4*BORDER_WIDTH
BOARD_HIGHT = WINDOW_HIGHT - 2*BORDER_WIDTH





