import pygame

MOUSE_EVENTS = (pygame.MOUSEBUTTONDOWN, pygame.MOUSEBUTTONUP, pygame.MOUSEMOTION)

CHANGE_TURN_EVENT = pygame.USEREVENT + 1

STONE_SELECTED_EVENT = pygame.USEREVENT + 2

FOCUS_ON_EVENT = pygame.USEREVENT + 3
FOCUS_OFF_EVENT = pygame.USEREVENT + 4